
name: Client App - Continuous Deployment

on:
  push:
    tags: ['client-app@*']

jobs:

  ci:
    uses: './.github/workflows/client-app-ci.yml'

  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/client-app

    needs: ci

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set APP_VERSION variable
        shell: pwsh
        run: |
          $appVersion = $ENV:GITHUB_REF_NAME.Replace('client-app@', '')
          echo "APP_VERSION=$appVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build for production
        run: |
          npm install
          npm version ${{ env.APP_VERSION }}
          npm run build-only

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: generic-client-app
          path: ./apps/client-app/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: generic-client-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy client app'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.54.0
          inlineScript: |
            az storage blob upload-batch --account-name "$CLIENT_APP_STORAGE_ACCOUNT" --destination '$web' --source ./dist --overwrite
        env:
          CLIENT_APP_STORAGE_ACCOUNT: ${{ vars.CLIENT_APP_STORAGE_ACCOUNT }}

          