
name: Client App - Continuous Deployment

on:
  push:
    tags: ['client-app@*']

jobs:

  ci:
    uses: './.github/workflows/client-app-ci.yml'

  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/client-app

    needs: ci

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: build for production
        run: |
          npm install
          npm run build-only

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: generic-client-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: generic-client-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        run: |
          echo 'push artifact to blob storage'

          