
name: Web Api - Continuous Deployment

on:
  push:
    tags: ['web-api@*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: generic-app-web-api:tatest

jobs:

  ci:
    uses: './.github/workflows/web-api-ci.yml'

  package:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./services/web-api
  #   permissions:
  #     contents: read
  #     packages: write
  #   needs: ci

  #   steps:
  #       uses: actions/checkout@v4

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./services/web-api
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  #   permissions:
  #     id-token: write #This is required for requesting the JWT